<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [565]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [566]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['Tenho uma reunião importante amanhã.', 'português'], ['Gosto de fazer caminhadas na natureza.', 'português'], ['Gosto de praticar esportes ao ar livre.', 'português'], ['I need to buy some groceries.', 'inglês'], ['Me gusta bailar salsa.', 'espanhol'], ['¿Me pasas la sal, por favor?', 'espanhol'], ['I want to learn French.', 'inglês'], ['A comida estava deliciosa!', 'português'], ['Quero aprender a tocar violão.', 'português'], ['Gosto de ouvir música clássica.', 'português'], ['Vamos sair para jantar no sábado.', 'português'], ['Preciso comprar leite e pão.', 'português'], ['This is a beautiful place.', 'inglês'], ['¿Cómo estuvo tu fin de semana?', 'espanhol'], ['Estou ansioso para as férias de verão.', 'português'], ['Estou aprendendo a cozinhar pratos novos.', 'português'], ['Estoy planeando unas vacaciones.', 'espanhol'], ['I enjoy playing soccer.', 'inglês'], ['Preciso resolver esse problema o mais rápido possível.', 'português'], ['¿Hablas español?', 'espanhol'], ['Quiero apre

O DataFrame do pandas facilita a visualização.

In [567]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0      Tenho uma reunião importante amanhã.  português
1    Gosto de fazer caminhadas na natureza.  português
2   Gosto de praticar esportes ao ar livre.  português
3             I need to buy some groceries.     inglês
4                    Me gusta bailar salsa.   espanhol
..                                      ...        ...
87             ¿Cuál es tu comida favorita?   espanhol
88             I'm excited for the concert.     inglês
89               I'm studying for my exams.     inglês
90               The weather is nice today.     inglês
91   Vou viajar para o exterior nas férias.  português

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [568]:
import re
import nltk
from nltk import ngrams
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('corpus')

# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"

def tamanhoMedioFrases(texto):
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
    
  return soma / len(tamanhos)

#
#   crie suas funções aqui
#
#

def obter_frquencia_ngrans(text, n):
  palavras = nltk.word_tokenize(text)
  
  ngrams_list = list(ngrams(palavras, n))
  
  freq = nltk.FreqDist(ngrams_list)

  return freq.N()

def obter_especial_chars(text):
  chars_especiais = len(re.findall(r"[^\w\s\.\,\u00C0-\u017F]", text))
  letras_com_acento = len(re.findall(r'[áéíóúãõâêîôûàèìòùäëïöüçñÁÉÍÓÚÃÕÂÊÎÔÛÀÈÌÒÙÄËÏÖÜÇÑ]', text))
  return chars_especiais + letras_com_acento

def obter_media_ngrans(text, n):
  palavras = nltk.word_tokenize(text)
  
  ngrams_list = list(ngrams(palavras, n))
  
  media = len(ngrams_list) / len(palavras)

  return media

def obter_letras_ngrams(text, n):
  palavras = nltk.word_tokenize(text)
  
  ngrams_list = list(ngrams(palavras, n))
  
  return ngrams_list

def count_stop_words(text, language):
  
  lang = ''
  
  if language == 'inglês':
    lang = 'english'
  elif language == 'espanhol':
    lang = 'spanish'
  else:
    lang = 'portuguese'
  
  stop_words = set(stopwords.words(lang))
  words = nltk.word_tokenize(text)
  count = sum(1 for word in words if word.lower() in stop_words)
  return count

def media_tamanho_palavras(text):
  words = nltk.word_tokenize(text)
  word_lengths = [len(word) for word in words]
  return sum(word_lengths) / len(word_lengths)

def diversidade_caracteres(text):
  return len(set(text)) / len(text)

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  texto = texto.lower()
  #print(texto)
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=obter_frquencia_ngrans(texto, 3)
  caracteristica3=obter_especial_chars(texto)
  caracteristica4=obter_media_ngrans(texto, 3)
  caracteristica5=count_stop_words(texto, frase[1])
  caracteristica6=media_tamanho_palavras(texto)
  caracteristica7=diversidade_caracteres(texto)
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, caracteristica2, caracteristica3, caracteristica4, caracteristica5, caracteristica6, caracteristica7, frase[1] ]
  return padrao

def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
    
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

[[6.2, 4, 2, 0.6666666666666666, 2, 5.333333333333333, 0.3888888888888889, 'português'], [5.333333333333333, 5, 0, 0.7142857142857143, 2, 4.714285714285714, 0.47368421052631576, 'português'], [4.571428571428571, 6, 0, 0.75, 2, 4.125, 0.38461538461538464, 'português'], [3.8333333333333335, 5, 0, 0.7142857142857143, 3, 3.4285714285714284, 0.5517241379310345, 'inglês'], [4.5, 3, 0, 0.6, 1, 3.8, 0.5909090909090909, 'espanhol'], [3.3333333333333335, 6, 2, 0.75, 2, 2.875, 0.5, 'espanhol'], [3.6, 4, 0, 0.6666666666666666, 2, 3.1666666666666665, 0.6086956521739131, 'inglês'], [5.5, 3, 1, 0.6, 2, 4.6, 0.5, 'português'], [5.0, 4, 1, 0.6666666666666666, 1, 4.333333333333333, 0.5666666666666667, 'português'], [5.2, 4, 2, 0.6666666666666666, 1, 4.5, 0.5806451612903226, 'português'], [4.5, 5, 1, 0.7142857142857143, 2, 4.0, 0.48484848484848486, 'português'], [4.6, 4, 1, 0.6666666666666666, 1, 4.0, 0.5, 'português'], [4.2, 4, 0, 0.6666666666666666, 3, 3.6666666666666665, 0.5384615384615384, 'inglês'],

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading corpus: Package 'corpus' not found in index


0  1  2         3  4         5         6          7
0   6.200000  4  2  0.666667  2  5.333333  0.388889  português
1   5.333333  5  0  0.714286  2  4.714286  0.473684  português
2   4.571429  6  0  0.750000  2  4.125000  0.384615  português
3   3.833333  5  0  0.714286  3  3.428571  0.551724     inglês
4   4.500000  3  0  0.600000  1  3.800000  0.590909   espanhol
..       ... .. ..       ... ..       ...       ...        ...
87  4.400000  4  3  0.666667  2  4.000000  0.642857   espanhol
88  3.666667  5  1  0.714286  3  3.428571  0.535714     inglês
89  3.333333  5  1  0.714286  3  3.142857  0.692308     inglês
90  4.200000  4  0  0.666667  2  3.666667  0.576923     inglês
91  4.428571  6  1  0.750000  3  4.000000  0.447368  português

[92 rows x 8 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [569]:
from sklearn.model_selection import train_test_split
import numpy as np

#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [570]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 72.46%
[[15  5  3]
 [ 1 17  4]
 [ 3  3 18]]
              precision    recall  f1-score   support

    espanhol       0.79      0.65      0.71        23
      inglês       0.68      0.77      0.72        22
   português       0.72      0.75      0.73        24

    accuracy                           0.72        69
   macro avg       0.73      0.72      0.72        69
weighted avg       0.73      0.72      0.72        69

métricas mais confiáveis
[[0 4 3]
 [0 6 2]
 [3 0 5]]
              precision    recall  f1-score   support

    espanhol       0.00      0.00      0.00         7
      inglês       0.60      0.75      0.67         8
   português       0.50      0.62      0.56         8

    accuracy                           0.48        23
   macro avg       0.37      0.46      0.41        23
weighted avg       0.38      0.48      0.43        23

